/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { forwardRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

const CarBody = forwardRef(({ args = [1.3, 0.8, 2.7], mass = 20, ...props }, ref) => {

  const { nodes, materials } = useGLTF('/models/Car/car_body.glb')
  const [, api] = useBox(() => ({ mass, args, velocity: [0, -15, 0], ...props }), ref)
  
  return (
    <group scale={2.2} ref={ref} api={api}>
      <group rotation={[0, -Math.PI / 2, 0]} position={[0, 0.21, 0]} scale={[0.19, 0.19, 0.29]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Vents} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.frontLights} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials.BackLights} />
        <mesh geometry={nodes.Cube003_5.geometry} material={materials.TireBay} />
        <mesh geometry={nodes.Cube003_6.geometry} material={materials.Suspension} />
        <mesh geometry={nodes.Cube003_7.geometry} material={materials.SmokeTubes} />
        <mesh geometry={nodes.Cube003_8.geometry} material={materials.SmokeTubeIn} />
        <mesh geometry={nodes.Cube003_9.geometry} material={materials.TopLights} />
        <mesh geometry={nodes.Cube003_10.geometry} material={materials['Top Lights Color']} />
        <mesh geometry={nodes.Cube003_11.geometry} material={materials['Top Light Rack']} />
      </group>
    </group>
  )
})

useGLTF.preload('/models/Car/car_body.glb')

export default CarBody