/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCylinder } from '@react-three/cannon'

const Wheel = forwardRef(({ radius = 0.7, leftSide, ...props }, ref) => {

  const { nodes, materials } = useGLTF('/models/Car/wheel.glb')
  useCylinder(() => ({ mass: 5, type: 'Kinematic', material: 'wheel', collisionFilterGroup: 0, args: [radius, radius, 0.5, 16], ...props }), ref)

  return (
    <group scale={1.2} ref={ref} >
      <group rotation={[ Math.PI / 2, 0, ((leftSide ? -1 : 1) * Math.PI) / 2]} scale={[0.28, 0.11, 0.28]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Wheel} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Wheel-1']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Wheel-2']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Wheel-3']} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.Nut} />
      </group>
    </group>
  )
})

useGLTF.preload('/models/Car/wheel.glb')

export default Wheel
