/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

export default function TheMan({args=[4.5, 3, 4.5] , ...props}) {
  const { nodes, materials } = useGLTF('/models/Statues/theMan.glb')

  const [ref] = useBox(() => ({mass: 1000, type: 'Static', args, ...props}))

  return (
    <group scale={0.7} ref={ref}>
      <group position={[0, 1.05, -0.68]} scale={[5.18, 4.55, 5.18]}>
        <primitive object={nodes.spine} />
        <primitive object={nodes.Bone} />
        <skinnedMesh geometry={nodes.Vert.geometry} material={nodes.Vert.material} skeleton={nodes.Vert.skeleton} />
      </group>
     {/*  <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[0, 4.75, 0]}
        scale={[1, 1, -0.02]}
      /> */}
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} scale={[3, 0.42, 3]} />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-0.57, 1.25, -0.47]}
        scale={[0.29, 0.23, 0.57]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[2.17, 9.7, 2.19]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.51, 0.05, 0.51]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[2.17, 9.7, 2.19]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.36, 0.04, 0.36]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[2.17, 9.7, 2.19]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.21, 0.02, 0.21]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-2.46, 9.55, 2.18]}
        rotation={[0, -0.54, 0]}
        scale={[1.12, 0.88, 0.03]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-1.34, 9.19, 2.7]}
        rotation={[0, -0.54, 0]}
        scale={[0.38, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-3.34, 10.07, 1.42]}
        rotation={[0, -0.54, 0]}
        scale={[0.15, 0.12, 0]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-3.34, 9.77, 1.42]}
        rotation={[0, -0.54, 0]}
        scale={[0.15, 0.12, 0]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-3.34, 9.46, 1.42]}
        rotation={[0, -0.54, 0]}
        scale={[0.15, 0.12, 0]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-2.74, 10.07, 1.94]}
        rotation={[0, -0.54, 0]}
        scale={[0.51, 0.12, 0.01]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-2.74, 9.72, 1.94]}
        rotation={[0, -0.54, 0]}
        scale={[0.51, 0.12, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/models/Statues/theMan.glb')
